### ISSUE TITLE
Broken links on site FAQ

### ISSUE THREAD

**Issue by Shawnecy** [gamercade-io/gamercade_site#6]
Initial condition: Load https://gamercade.io/faq/.
Expected behavior: Clicking on links like "What is Gamercade?" or "downloads" should take me to those pages.
Actual behavior: Arrive at "Page not found" page.

Notes:
My guess is it's because docusaurus.config.js maps the faq.md document to the `/faq` path but the md file assume that the other documents are at the same path as its own.

**Comment by RobDavenport** [comment]
Thanks for the report! This is an interesting one for sure.

**Comment by RobDavenport** [comment]
Should be resolved in [b05e7b32cd6a74bfa074f505a6cd7fe578349bfa](https://github.com/gamercade-io/gamercade_site/commit/b05e7b32cd6a74bfa074f505a6cd7fe578349bfa)
